T05 29 game
boorav4ik/praktikum pull request #10
Opened 2023-03-07 14:58 UTC by viktor-nonjme

Теперь игра ломается, только когда все клетки заняты цифрами )

2023-03-09 09:05 UTC, EzhikTT commented on packages/client/src/components/GameField.tsx
> +    ctx.fillText(String(cell.value), cell.x + width / 2, cell.y + width / 1.5);
Округление не нужно?

2023-03-09 09:07 UTC, EzhikTT requested changes
А как здесь появился `package-lock.json`?

2023-03-09 09:07 UTC, EzhikTT commented on packages/client/src/components/GameField.tsx
> +            break;
Вот это очень некрасиво. Для выхода из цикла использовать `break` очень плохо и считается бедманерством и антипаттерном

2023-03-09 09:07 UTC, EzhikTT commented on packages/client/src/components/GameField.tsx
> +    default:
А зачем `default`, если выше задается дефолтное значение?

2023-03-09 09:51 UTC, viktor-nonjme commented on packages/client/src/components/GameField.tsx
> +    default:
линтер заставил

2023-03-09 09:52 UTC, viktor-nonjme commented on packages/client/src/components/GameField.tsx
> +    default:
и впихнул первое попавшееся

2023-03-09 09:55 UTC, viktor-nonjme commented on packages/client/src/components/GameField.tsx
> +            break;
буду делать отдельный хук или переводить на классовый компонент. сделал а бы сделать хоть как то ) это полу рабочее решение, знаю )

2023-03-10 13:00 UTC, boorav4ik commented on packages/client/src/components/GameField.tsx
> +import { useEffect, useRef, useState, useCallback, memo } from 'react';
форматирование

2023-03-10 20:48 UTC, tayru approved these changes

2023-03-11 10:30 UTC, LapEv approved these changes

2023-03-11 10:30 UTC, LapEv commented on packages/client/src/components/GameField.tsx
> +  const [width, setWidth] = useState(500 / size - 6);
тоже самое касается и самого size, setSize нигде не используется.

2023-03-13 05:55 UTC, EzhikTT requested changes

2023-03-13 05:55 UTC, EzhikTT commented on packages/client/src/components/GameField.tsx
> +export function GameField(props: any) {
А мб стоит оставить в этом файле только компонент? А то получается слишком долго до него листать, и функции не нужны прям в этом файле. А лучше создать класс со статическими методами этими всеми, которые выше компонента

2023-03-13 05:55 UTC, EzhikTT commented on packages/client/src/components/GameField.tsx
> +            break;
Для таких случаев оставляйте [команда] `TODO <почему оно существует>`, тогда вопросов не будет

2023-03-13 05:55 UTC, EzhikTT commented on packages/client/src/components/GameField.tsx
> +    default:
Какой он бяка((( Тогда убери 37 строку, где задаешь такое же значение

2023-03-13 05:56 UTC, EzhikTT commented
И, наверное, надо убрать `Draft` с ПРа

2023-03-17 11:17 UTC, EzhikTT commented
А что с этим ПРом? С ним какие-то проблемы?

2023-03-17 12:33 UTC, viktor-nonjme commented
> А что с этим ПРом? С ним какие-то проблемы?

Вчера начал переделывать, сегодня - завтра доделаю

2023-03-19 12:19 UTC, closed without merging