T 05 15 forum page
boorav4ik/praktikum pull request #12
Opened 2023-03-11 08:59 UTC by Replicatus

### Какую задачу решаем
Страница разделов форума
Страница тем раздела 
Страница темы с ответами и самим текстом

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-11 10:57 UTC, boorav4ik requested changes

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/App.tsx
> +            />
Думаю, лучше сделать вложенные роуты:
```jsx
<Route path="/forum">
  <Route index element={<ForumPage />} />
  <Route path="/:theme_name">
    <Route index element={<ThemePage />} />
    ...
  </Route>
</Route>
```

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/ForumRow/index.tsx
> +export const ColorButton = styled(Button)<ButtonProps>(({ theme }) => ({
Решили писать обычные функции, а не стрелочные
Это касается всего кода

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/GameBoard.tsx
> +        sx={{ fontSize: 24 }}
Это не относится к твоей задаче
Скорее всего, это преттир поправил.
Лучше убрать из твоей ветки

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/HeaderForPage/index.tsx
> +  // }
думаю можно залить без этого

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/NavBar.tsx
> +        </Button>
Лучше это тоже не заливай, к твоей задаче этот файл не относится.
я в своей задаче с роутами уже добавил переход на страницу форума
у тебя потом будет много конфликтов при слиянии

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/ThemeBranchMessage/index.tsx
> +      <div style={{ textAlign: 'end' }}>{user.name}</div>
Лучше использовать  mui: 
```jsx
<Box sx={{...}}>....</Box>
```

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/ThemeBranchMessage/index.tsx
> +      <div>{text}</div>
Для текста используем `Typography`

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/main.tsx
> +console.log(theme)
вообще можно удалить этот консольлог (я случайно оставил)
уже сделал это в своей ветке
можешь тоже не заливать это в свою ветку

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/HeaderForPage/index.tsx
> +// import { useNavigate } from 'react-router-dom'
Забыл убрать

2023-03-11 10:57 UTC, boorav4ik commented on packages/client/src/components/NavBar.tsx
> +  }
вроде решили навигацию делать [так](https://github.com/boorav4ik/praktikum/blob/T05-32/redux-store/packages/client/src/components/LinkButton.tsx):
```jsx
<Button component={Link} to="/path-to-page">
  LinkButton
</Button>
```

2023-03-11 11:58 UTC, LapEv approved these changes
ИМХО
В целом, было бы неплохо консолидировать все компоненты форума в свою отдельную папку. 
Для лучшей читабельности кода, разделять функции пустой строкой. К примеру, в ThemeBranch.tsx я отметил это.

2023-03-11 11:58 UTC, LapEv commented on packages/client/src/pages/Forum.tsx
> +const ForumPage: Props = () => {
не понимаю, зачем отдельно type выводить и просто оставить так:
const ForumPage: FC = () => {

2023-03-11 11:58 UTC, LapEv commented on packages/client/src/pages/Themes.tsx
> +type Props = FC
здесь тоже самое

2023-03-11 11:58 UTC, LapEv commented on packages/client/src/pages/ThemeBranch.tsx
> +  return (
ИМХО, для лучше читабельности кода, разделять функции пустой строкой.

2023-03-11 12:44 UTC, Replicatus commented on packages/client/src/pages/ThemeBranch.tsx
> +type Props = FC
Ну тут вопрос к теории практикума, там же приводится вариант что в случае добавления пропсов, всегда так будет удобней добавить. Решил так же делать или так не пишут все таки?

2023-03-11 13:37 UTC, boorav4ik commented on packages/client/src/pages/ThemeBranch.tsx
> +type Props = FC
Можешь скрин скинуть или ссылку, где в теории это написано?
На ум приходит только это:
[Screenshot_20230311-163212.png](https://user-images.githubusercontent.com/67604789/224487603-de48ce8f-aaf3-48b6-a7f4-11382d5d2351.png)
Но тут вообще о другом.

Вроде ты определяешь элемент, а тип у него почему-то  `Props`. 

Перепиши на обычные функции. А пропсы и типы им будем добавлять, если они понадобятся

2023-03-11 15:08 UTC, Replicatus commented on packages/client/src/pages/ThemeBranch.tsx
> +type Props = FC
Ссылка была [вот](https://practicum.yandex.ru/learn/middle-frontend/courses/cc822dfe-3f49-42ef-8efd-152e1f4006fe/sprints/92364/topics/afbb822a-5d66-41f6-b055-323fd41f6afb/lessons/829f121f-5114-48e1-93e2-284d2ec950c2/).

ну и да, если их нужно экспортить, то и название норм давать.

2023-03-11 16:27 UTC, boorav4ik commented on packages/client/src/pages/ThemeBranch.tsx
> +type Props = FC
Тоже что и на моëм скрине.

А их нужно будет экспортить?

И ты задаëшь тип с именем `Props`. В реакте пропс - это первый аргумент компонента. А ты самому компоненту этот тип присвоил.

2023-03-12 09:48 UTC, tayru approved these changes

2023-03-12 09:51 UTC, viktor-nonjme approved these changes

2023-03-13 05:58 UTC, EzhikTT commented on packages/client/src/components/forum/ForumRow/index.tsx
> +  return (
Если перенести начало компонента на строчку с `return`, то круглые скобки не нужны

2023-03-13 05:59 UTC, EzhikTT commented on packages/client/src/App.tsx
> +    // const fetchServerData = async () => {
Зачем комментировать код, если он под гитом?

2023-03-13 05:59 UTC, EzhikTT approved these changes
Все ок

2023-03-13 08:19 UTC, boorav4ik requested changes

2023-03-13 08:19 UTC, boorav4ik commented on packages/client/src/App.tsx
> +    // fetchServerData()
Нужно вернуть как было

2023-03-13 08:19 UTC, boorav4ik commented on packages/client/src/App.test.tsx
> +  expect(screen.getByTestId('App')).toBeDefined()
лучше не заливай, те изменения, которые не касаются твоей задачи. Верни, плиз, как было.
Поправим, когда будем делать рефактор

2023-03-13 08:19 UTC, boorav4ik commented on packages/client/src/components/NavBar.tsx
> +        <Button key="profile">Профиль</Button>
Спасибо, что заметил))
но лучше не заливать это в твоей ветке.
такие мелкие вещи можно собрать какой-то отдельный ПР

2023-03-13 08:34 UTC, boorav4ik requested changes

2023-03-13 08:34 UTC, boorav4ik commented on packages/client/src/pages/Main.tsx
> +      <Box sx={{ my: 10, display: 'flex', justifyContent: 'center' }}>
это тоже не относится к твоей задаче

2023-03-13 08:34 UTC, boorav4ik commented on packages/client/src/utils/isObject.ts
> +  )
и это
если хочешь, создай сам ветку fix/format и залей туда все эти правки, даже ревьювить не будем, сразу сольём

2023-03-14 09:32 UTC, boorav4ik requested changes

2023-03-14 09:32 UTC, boorav4ik commented on packages/client/src/App.tsx
> +
Удали, плиз, не стоит это заливать

2023-03-14 09:36 UTC, boorav4ik approved these changes

2023-03-14 09:36 UTC, merged