Feat/t05 15 authentication&authorization
boorav4ik/praktikum pull request #13
Opened 2023-03-12 19:45 UTC by LapEv

Аутентификация и Авторизация

Добавил запросы к серверу через axois:
    SIGNIN: 'auth/signin',
    SIGNUP: 'auth/signup',
    SIGNOUT: 'auth/logout',
    USER_INFO: 'auth/user',
Добавил в useAuth соответствующие обработки
Добавил страницу регистрации
Добавил в layout Main - NavBar смену Войти/Выйти в зависимости от наличия входа в систему.

2023-03-13 06:08 UTC, EzhikTT requested changes

2023-03-13 06:08 UTC, EzhikTT commented on packages/client/src/hoks/RequaredAuth.tsx
> +import { Navigate, useLocation } from 'react-router-dom'
А что за название папки такое странное? Хотели `HOC` или `hook`?)

2023-03-13 06:08 UTC, EzhikTT commented on packages/client/src/api/config.ts
> +export const API_ENDPOINTS = {
А почему это константы в `SCREAMING_SNAKE_CASE`, а роуты в файле выше - нет?

2023-03-13 20:13 UTC, LapEv commented on packages/client/src/components/NavBar.tsx
> +  Профиль: Routes.Profile,
этот компонент удален (дубль). В первоначальном всё как надо

2023-03-13 20:13 UTC, LapEv commented on packages/client/src/hooks/useAuth.tsx
> +    authData: {
сделано

2023-03-13 20:13 UTC, LapEv commented on packages/client/src/hoks/RequaredAuth.tsx
> +import { Navigate, useLocation } from 'react-router-dom'
НОС - исправлено

2023-03-13 20:16 UTC, LapEv commented on packages/client/src/api/config.ts
> +export const API_ENDPOINTS = {
поправил как у всех.

2023-03-14 13:44 UTC, EzhikTT approved these changes
Все ок

2023-03-14 22:20 UTC, boorav4ik requested changes

2023-03-14 22:20 UTC, boorav4ik commented on packages/client/src/store/reducers/auth/index.ts
> +export const { changeProfile } = authSlise.actions
тоже самое что в `store/slices/auth/index.ts`
~~в конце останется тольк один~~ думаю, этот файл можно удалить

2023-03-14 22:20 UTC, boorav4ik commented on packages/client/src/store/slices/auth/index.ts
> +  user: User | null
в ветке девелоп используется тип Nullable
видимо, что-то  недозалил

2023-03-14 22:20 UTC, boorav4ik commented on packages/client/src/hooks/interfaces/authActions.ts
> +      phone: string
у тебя же определён тип `SignUp`

2023-03-15 18:53 UTC, LapEv commented on packages/client/src/store/reducers/auth/index.ts
> +export const { changeProfile } = authSlise.actions
удалил

2023-03-15 18:53 UTC, LapEv commented on packages/client/src/store/slices/auth/index.ts
> +  user: User | null
исправил

2023-03-15 18:53 UTC, LapEv commented on packages/client/src/hooks/interfaces/authActions.ts
> +      phone: string
исправил

2023-03-15 19:42 UTC, boorav4ik requested changes
Всë круто.
Но в одном месте нужно вернуть, как было
Остальные мои коменты, на твоë усмотрение.

2023-03-15 19:42 UTC, boorav4ik commented on packages/client/src/api/userApi.ts
> +      phone,
Может здесь просто написать `signUpData`?

2023-03-15 19:42 UTC, boorav4ik commented on packages/client/src/layouts/Main/navBar.tsx
> +        )}
Можно заменить одной кнопкой, у которой будет `onClick={() => user && signout()}` и текст `{user ? 'Выйти' : 'Войти'}`

2023-03-15 19:42 UTC, boorav4ik commented on packages/client/src/store/slices/auth/interfaces.ts
> +  avatar: Nullable<string>
Можешь тут вернуть как было?

2023-03-15 19:42 UTC, boorav4ik commented on packages/client/src/api/userApi.ts
> +  async ({ login, password }: Login, thunkAPI) => {
`{ login, password}` можно заменить на  loginData

2023-03-15 19:50 UTC, LapEv commented on packages/client/src/api/userApi.ts
> +      phone,
Да, согласен, так лаконичнее

2023-03-15 19:50 UTC, LapEv commented on packages/client/src/api/userApi.ts
> +  async ({ login, password }: Login, thunkAPI) => {
Да, согласен, так лаконичнее

2023-03-15 19:50 UTC, LapEv commented on packages/client/src/store/slices/auth/interfaces.ts
> +  avatar: Nullable<string>
вернул как было

2023-03-15 19:52 UTC, LapEv commented on packages/client/src/layouts/Main/navBar.tsx
> +        )}
Спасибо за подсказку. Честно говоря, не знал, что такая конструкция user && signout() работает

2023-03-15 19:59 UTC, boorav4ik commented on packages/client/src/store/slices/auth/interfaces.ts
> +  avatar: Nullable<string>
Не не так)) видишь гит показывает изменения, значит не как было)) 
Не буду тебя больше мучить, сам верну

2023-03-15 20:03 UTC, boorav4ik commented on packages/client/src/layouts/Main/navBar.tsx
> +        )}
выполнение цепочки с оператором `&&` заканчивается на первой лжи. Если у нас нет юзера, точнее он равен  null, то функция просто вернëт null в никуда.

2023-03-15 20:05 UTC, boorav4ik approved these changes

2023-03-16 18:48 UTC, merged