T05 29 game
boorav4ik/praktikum pull request #18
Opened 2023-03-19 12:32 UTC by viktor-nonjme

### Какую задачу решаем

- Ядро игры

### Скриншоты/видяшка

<img width="1792" alt="Снимок экрана 2023-03-19 в 15 23 42" src="https://user-images.githubusercontent.com/57726054/226175082-74edf488-a005-4213-b121-cb62cd0c89f1.png">

### TBD

- Поиск багов
- Поиск правильной практики работы с предыдущим стейтом в компоненте
- Другой вариант старта и завершения игры
- Добавить счёт баллов

2023-03-19 12:53 UTC, viktor-nonjme commented
Тесты шо та напутали 
https://caniuse.com/mdn-api_canvasrenderingcontext2d_roundrect

2023-03-20 12:37 UTC, EzhikTT commented on packages/client/src/components/GameBoard.tsx
> +  // Временное решение, в main.tsx закомитил strictmode
Еще добавить `TODO` в начало)

2023-03-20 12:38 UTC, EzhikTT commented on packages/client/src/game/components/Canvas.tsx
> +  canvasHeight: number
Можно было объединить свойства без пробелов. И добавить уровень доступа

2023-03-20 12:43 UTC, EzhikTT commented on packages/client/src/game/utils/index.ts
> +  return PALETTE[String(value)]
Можно было в шаблонную строку завернуть через апострофы

2023-03-20 12:43 UTC, EzhikTT requested changes
Явно лишние `.DS_Store` и `package-lock.json`

2023-03-20 12:43 UTC, EzhikTT commented on packages/client/src/game/components/Canvas.tsx
> +  canvasRef
Почему здесь нет типа? И в стейте

2023-03-20 16:23 UTC, tayru approved these changes

2023-03-21 22:03 UTC, boorav4ik requested changes

2023-03-21 22:03 UTC, boorav4ik commented on packages/client/package.json
> +    "canvas": "^2.11.0",
А версию кто фиксировать будет?

2023-03-22 02:48 UTC, viktor-nonjme commented on packages/client/src/game/old/index.tsx
> +  }
предлагаю читать название файлов )

2023-03-22 02:58 UTC, viktor-nonjme commented on packages/client/src/game/components/Canvas.tsx
> +    }
прочитай про требования к прошлому модулю, оформления кода. чего они тут поменялись ?

2023-03-22 06:31 UTC, boorav4ik requested changes

2023-03-22 06:31 UTC, boorav4ik commented on .gitignore
> +.DS_Store
можешь у себя в коде оставить, но зачем это заливать сюда

2023-03-22 06:31 UTC, boorav4ik commented on packages/client/src/game/components/Canvas.tsx
> +    }
~~Не помню требования писать как можно больше кода~~
На какие именно требования ты ссылаешься?

2023-03-22 06:31 UTC, boorav4ik commented on packages/client/src/game/old/index.tsx
> +  }
никогда не слышал, что есть магические названия файлов, которые можно комитить, но их не должны ревьювить. Просвятишь?
если этот код устарел и не использутся, не заливай сюда
если он важен, то залей в отдельную ветку, чтоб можно было к нему вернуться

2023-03-22 06:31 UTC, boorav4ik commented on packages/client/src/game/utils/index.ts
> +        }
Можно заменить
```tsx
isNext = cells[j][i].value === cells[j][i + 1].value
```

2023-03-22 06:31 UTC, boorav4ik commented on packages/client/src/game/utils/index.ts
> +  for (let i = 0; i < len; i++) {
`array.lenght` не вычисляется, а просто хранится в массиве, затраты ресурсов на его получения такие же, как на чтение переменной
нет смысла его отдельно хранить
особенно учитывая, что длину ты получаешь у одного массива, а используешь её для прохода по двум разным
возможно они равны по длинне, но если вдруг это будет не так, то игра сломается

2023-03-22 06:31 UTC, boorav4ik commented on packages/client/src/game/utils/index.ts
> +    }
```tsx
fullfied = Boolean(cells[i][j].value)
```

2023-03-22 06:31 UTC, boorav4ik commented on packages/client/src/game/utils/index.ts
> +    for (let j = 0; j < len; j++) {
про длину массива написал ниже
может привести к падению игры, нужно исправить

2023-03-22 07:35 UTC, closed without merging