замена стрелок
boorav4ik/praktikum pull request #19
Opened 2023-03-19 16:10 UTC by tayru

### Какую задачу решаем
Замена  стрелок на обычные функции для единого стиля компонент

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-03-20 08:12 UTC, boorav4ik requested changes

2023-03-20 08:12 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +export function ProfileHeader({ ChooseFile, fileData }: ProfileHeaderProps) {
переменуй, `ChooseFile` в `onChooseFile` допустим
в js принято имена переменных начинать с маленькой буквы и использовать [camelCase](https://www.w3schools.com/js/js_conventions.asp)
я знаю, что это не ты так написал, и так было, но я в задаче попросил переименовать.

2023-03-20 08:36 UTC, tayru commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +export function ProfileHeader({ ChooseFile, fileData }: ProfileHeaderProps) {
сделал

2023-03-20 09:44 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +export function ProfileHeader({ ChooseFile, fileData }: ProfileHeaderProps) {
саму константу при объявлении тоже переименуй, пожалуйста

2023-03-20 17:01 UTC, tayru commented
> А почему стрелочные функции везде изменились на обычные?
Команда договорилась использовать в стиле обычные функции

2023-03-20 19:42 UTC, merged

2023-03-23 06:44 UTC, EzhikTT commented
А почему этот ПР влит, никем не апрувнутый?