test pr
boorav4ik/praktikum pull request #20
Opened 2023-03-19 23:04 UTC by boorav4ik

## test game

2023-03-20 12:38 UTC, boorav4ik commented on packages/client/src/game/components/Canvas/hooks/useCells.ts
> +    output[index(Math.floor(Math.random() * isMoved.size), 3)] = 2
output[isMoved.get(index(Math.floor(Math.random() * isMoved.size)), 3)] = 2

2023-03-21 20:42 UTC, tayru approved these changes

2023-03-22 19:53 UTC, LapEv approved these changes

2023-05-09 05:03 UTC, viktor-nonjme approved these changes

2023-05-10 03:34 UTC, Replicatus approved these changes

2023-05-11 05:29 UTC, EzhikTT commented on packages/client/src/components/Audio.tsx
> +  const audio = useMemo(() => {
Для этого лучше использовать `useCallback`

2023-05-11 05:31 UTC, EzhikTT commented on packages/client/src/components/FloatingActionButton.tsx
> +type FabProps = {
Можно было расширить тип из реакта `PropsWithChildren`

2023-05-11 05:34 UTC, EzhikTT commented on packages/client/src/game/components/Canvas/index.tsx
> +import { type ArrowDirection } from '../../utils/ArrowDirections'
`type` лучше писать перед фигурными скобками

2023-05-11 05:37 UTC, EzhikTT requested changes

2023-05-11 05:37 UTC, EzhikTT commented on packages/client/src/game/components/Canvas/utils/Canvas.ts
> +function drawRoundSquare(
А почему все эти методы не объединили в класс?

2023-05-11 05:37 UTC, EzhikTT commented on packages/client/src/game/components/Canvas/index.tsx
> +  }, [...cells])
Зачем декомпозировать? Должно и без спреда работать корректно

2023-05-11 05:37 UTC, EzhikTT commented on packages/client/src/components/Game/GameBoard.tsx
> +  function resetGame() {
А почему не стрелочные функции тут везде?

2023-05-11 05:37 UTC, EzhikTT commented on packages/client/src/components/Game/GameBoard.tsx
> +import { ArrowDirection } from '../../game/utils/ArrowDirections'
А алиасов на пути нет?

2023-05-11 05:37 UTC, EzhikTT commented on packages/client/src/components/Button.tsx
> +import MuiButton, { ButtonProps as ButtonProps } from '@mui/material/Button'
А чем отличается алиас от названия?

2023-05-11 22:02 UTC, boorav4ik commented on packages/client/src/game/components/Canvas/utils/Canvas.ts
> +function drawRoundSquare(
обернул.

2023-05-11 22:03 UTC, boorav4ik commented on packages/client/src/game/components/Canvas/index.tsx
> +import { type ArrowDirection } from '../../utils/ArrowDirections'
Ок. Поправил

2023-05-11 22:03 UTC, boorav4ik commented on packages/client/src/components/FloatingActionButton.tsx
> +type FabProps = {
Готово

2023-05-11 22:10 UTC, boorav4ik commented on packages/client/src/components/Audio.tsx
> +  const audio = useMemo(() => {
Я видимо чего-то не понимаю. Можно позвать пояснительную команду?
-----
Хотел, чтоб аудио добавлялось только один раз. и хранилось в переменной. Нужно рендерить `audio` как компонент и завернуть это в `useCallback`? Или как? `useCallback` каждый раз создаёт новое аудио. Может как-то подругому надо?
Переписал вообще без хуков.

2023-05-11 22:11 UTC, boorav4ik commented on packages/client/src/game/components/Canvas/index.tsx
> +  }, [...cells])
Убрал

2023-05-11 22:23 UTC, boorav4ik commented on packages/client/src/components/Game/GameBoard.tsx
> +  function resetGame() {
вроде хуки принято писать вначале, потом константы  и функции, потом юзЭфекты. Но это не точно.
функция `shift` определяется ниже хука `useArrow`, в который передаётся. Поэтому она должна всплывать.
остальные не стрелочные для единообразия
исправил

2023-05-11 22:50 UTC, boorav4ik commented on packages/client/src/components/Game/GameBoard.tsx
> +import { ArrowDirection } from '../../game/utils/ArrowDirections'
не было. Добавил.

2023-05-11 22:51 UTC, boorav4ik commented on packages/client/src/components/Button.tsx
> +import MuiButton, { ButtonProps as ButtonProps } from '@mui/material/Button'
Видимо, я что-то хотел умное написать, но потом передумал.

Удалил

2023-05-16 05:01 UTC, EzhikTT commented on packages/client/src/components/Game/GameBoard.tsx
> +  function resetGame() {
Ну такого жесткого правила нет. И эта функция не выглядит как той, которой нужно всплытие, тк она все равно используется только в компоненте

2023-05-16 05:01 UTC, EzhikTT approved these changes
Вес ок

2023-05-18 13:04 UTC, merged