T05 36 adaptiv
boorav4ik/praktikum pull request #21
Opened 2023-03-20 08:17 UTC by tayru

### Какую задачу решаем
Добавлена адаптивность менюшек - на больших экранах включаем хедер, добавляем кнопки войти и регистрация.
На маленьких показываем сайдбар, отображаем кнопку войти в свернутом режиме, сайдбар выезжает поверх поля не сдвигая его.

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/20746367/226283212-4a621ed2-797d-4591-8cd4-98b28ec90ba0.png)
![image](https://user-images.githubusercontent.com/20746367/226283255-7b3769d7-b7ba-4d00-b1c2-d984817ef37c.png)
![image](https://user-images.githubusercontent.com/20746367/226283271-a0a10f3b-2aef-4b67-a3fd-1be1f3120c5f.png)

### TBD (если есть)

2023-03-20 09:39 UTC, boorav4ik requested changes

2023-03-20 09:39 UTC, boorav4ik commented on packages/client/src/layouts/Main/loginButtons/RegButton.tsx
> +}
кажется, тут форматирование поехало

2023-03-20 09:39 UTC, boorav4ik commented on packages/client/src/layouts/Main/loginButtons/index.tsx
> +      </div>
предлагаю `div` в `Box`, a `style` на `sx`
а ещё зафиксировать ширину контейнера, чтоб остальные кнопки не ехали, если мы не показываем `RegButton`

2023-03-20 09:39 UTC, boorav4ik commented on packages/client/src/layouts/Main/loginButtons/RegButton.tsx
> +           <Button
посмотри в наших компонентах есть `LinkButton`
можно не использовать хук `useNavigate`, а пробросить `Link` из `react-router-dom` как пропс `component` в кнопку
Мы на одном из созвонов это обсуждали, и вроде решили так делать.

- нет хуков
- когда наводишь курсор на такую кнопку, внизу показывается адрес перехода
- выглядит лаконичнее

2023-03-20 09:39 UTC, boorav4ik commented on packages/client/src/layouts/Main/loginButtons/RegButton.tsx
> +           <Button
и если использовать готовый компонент, можно для каждой кнопки не создавать отдельный файл

2023-03-20 09:39 UTC, boorav4ik commented on packages/client/src/layouts/Main/navBar.tsx
> +    >
Можно убрать пропс `style`, а его значение добавить к просу `sx`

2023-03-20 12:46 UTC, EzhikTT commented on packages/client/src/layouts/Main/index.tsx
> +    position: 'absolute',
А для автоформатирования при пуше у вас ничего не стоит?

2023-03-20 12:47 UTC, EzhikTT requested changes

2023-03-20 12:47 UTC, EzhikTT commented on packages/client/src/layouts/Main/loginButtons/AuthButton.tsx
> +import { Routes } from '../../../utils/routes'
А вы алиасы не настраивали на пути подключения?

2023-03-20 17:24 UTC, tayru commented on packages/client/src/layouts/Main/index.tsx
> +    position: 'absolute',
нет, у кого-то в вс-коде стоит при сохранении запуск, у меня пхпшторм, там не настраивал

2023-03-20 19:57 UTC, tayru commented on packages/client/src/layouts/Main/drawerBarData.tsx
> +
прогнал через преттир

2023-03-20 20:00 UTC, tayru commented on packages/client/src/layouts/Main/navBar.tsx
> +    >
+

2023-03-21 07:22 UTC, Replicatus approved these changes

2023-03-21 18:10 UTC, tayru commented on packages/client/src/layouts/Main/loginButtons/AuthButton.tsx
> +import { Routes } from '../../../utils/routes'
алиасов на текущий момент нет

2023-03-21 19:45 UTC, tayru commented on packages/client/src/layouts/Main/loginButtons/RegButton.tsx
> +           <Button
сделано

2023-03-21 19:45 UTC, tayru commented on packages/client/src/layouts/Main/loginButtons/index.tsx
> +      </div>
сделано

2023-03-21 21:14 UTC, boorav4ik approved these changes
Всё ок
Нужно будет контейнер и бокс с рамкой вынести в мэйн лэйаут

2023-03-23 06:46 UTC, EzhikTT requested changes
А почему вы алиасы не настроите, чтобы не писать относительные пути?

2023-03-23 21:08 UTC, merged