Feat/t05 34 refactor profile page
boorav4ik/praktikum pull request #22
Opened 2023-03-21 16:46 UTC by LapEv

Добавлено взаимодействие страницы профиля со стором
Добавлена смена пароля
Добавлена валидация полей страницы профиля и смены пароля
![image](https://user-images.githubusercontent.com/51084295/226679835-fd3fc33f-8278-48b4-8d1a-629a276d8efc.png)
![image](https://user-images.githubusercontent.com/51084295/226680006-ac7d8b36-9883-41e9-875b-375509977019.png)

2023-03-21 21:09 UTC, boorav4ik commented
тест падает
```
Argument of type '{ first_name: string; second_name: string; display_name: string; login: string; email: string; password: string; phone: string; }' is not assignable to parameter of type 'User'.
      Object literal may only specify known properties, and 'password' does not exist in type 'User'.
```

2023-03-22 12:54 UTC, LapEv commented on packages/client/src/store/slices/auth/interfaces.ts
> +  avatar?: stringOrNull
Исправлено

2023-03-23 06:51 UTC, EzhikTT commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePassword.tsx
> +      return !value ? { ...acc, ...{ [field]: value } } : acc
можно было в одну строчку

2023-03-23 06:56 UTC, EzhikTT requested changes
Замечания по всем файлам типовые

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/pages/Profile/ProfileFields.tsx
> +      error={error && error.length ? true : false}
Зачем тут явное упоминание `true` и `false`?

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/pages/Profile/ProfileChangePassword/enumInputFields.ts
> +export enum EnumPasswordFields {
А почему этот `Enum` н используется выше, где проверяется имя инпута в валидации формы?

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePasswordFields.tsx
> +      value={value[name as keyof typeof value]}
Аналогично с комментом выше

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePassword.tsx
> +          error={errors[name as keyof typeof errors]}
Здесь точно нужна такая конструкция? Нельзя типизировать `name`?

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/pages/Profile/Profile.tsx
> +          ChooseFile={onChooseFile}
Почему пропс в `PascalCase`?

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/api/user.ts
> +export const getUser = createAsyncThunk('user/getuser', async (_, thunkAPI) => {
Почему тут не `camelCase`?

2023-03-23 06:56 UTC, EzhikTT commented on packages/client/src/api/user.ts
> +import $host from '.'
Очень странный импорт. Почему из индекса, а не из файла конкретного?

2023-03-23 15:17 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileFields.tsx
> +      error={error && error.length ? true : false}
исправлено

2023-03-23 15:17 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePassword.tsx
> +      return !value ? { ...acc, ...{ [field]: value } } : acc
исправлено

2023-03-23 15:17 UTC, LapEv commented on packages/client/src/pages/Profile/Profile.tsx
> +          ChooseFile={onChooseFile}
исправлено

2023-03-23 15:17 UTC, LapEv commented on packages/client/src/api/user.ts
> +export const getUser = createAsyncThunk('user/getuser', async (_, thunkAPI) => {
исправлено

2023-03-23 15:17 UTC, LapEv commented on packages/client/src/api/user.ts
> +import $host from '.'
исправлено

2023-03-23 15:20 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileChangePassword/enumInputFields.ts
> +export enum EnumPasswordFields {
у меня только в этом месте enum. В остальных использую перебор массива через map

2023-03-24 10:22 UTC, boorav4ik requested changes
круто
небольшие замечания по стилю кода

2023-03-24 10:22 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePassword.tsx
> +}
Договорились использовать обычные функции, а не стрелочные

2023-03-24 10:22 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +          onChange={(event: ChangeEvent<HTMLInputElement>) => сhooseFile(event)}
можно писать так:
```tsx
onChange={сhooseFile}
```
 `сhooseFile` получит все аргументы из `onChange`

2023-03-24 10:22 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +          src={fileData ? (fileData as string) : `${AvatarHost}${avatar}`}
кажется, можно короче ~~но не обязательно~~
```tsx
src={(fileData ??  `${AvatarHost}${avatar}`) as string}
```

2023-03-24 10:22 UTC, boorav4ik commented on packages/client/src/utils/isEmptyObject.ts
> +    }
можно объединить в одно условие через `&&`
но необязательно

2023-03-24 17:14 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePassword.tsx
> +          error={errors[name as keyof typeof errors]}
исправлено

2023-03-24 17:18 UTC, LapEv commented on packages/client/src/pages/Profile/Profile.tsx
> +          сhooseFile={onChooseFile}
Исправил

2023-03-24 17:18 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileChangePassword/ProfileChangePassword.tsx
> +}
Пропустил. Исправил

2023-03-24 17:20 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +          onChange={(event: ChangeEvent<HTMLInputElement>) => сhooseFile(event)}
Забываю об этом, исправил.

2023-03-24 17:20 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +          src={fileData ? (fileData as string) : `${AvatarHost}${avatar}`}
Забываю об этой ??, исправил.

2023-03-24 17:23 UTC, LapEv commented on packages/client/src/utils/isEmptyObject.ts
> +    }
Исправил

2023-03-24 18:12 UTC, boorav4ik commented on packages/client/src/store/slices/auth/interfaces.ts
> +}
Ты просто один раз объявил тип:
```tsx
type NullableString = NullableString<string>
```
И используй его везде
Я заправлю, но лучше тоже исправить

2023-03-25 08:28 UTC, LapEv commented on packages/client/src/store/slices/auth/interfaces.ts
> +}
Поправил

2023-03-25 12:48 UTC, merged