T05 53 add web apis
boorav4ik/praktikum pull request #27
Opened 2023-04-04 09:22 UTC by viktor-nonjme

### Какую задачу решаем

- Добавлено полноэкранное апи

### Скриншоты
<img width="1792" alt="Снимок экрана 2023-04-04 в 12 21 17" src="https://user-images.githubusercontent.com/57726054/229747648-bc74810d-bb48-4116-bd4d-af8d43be4f62.png">

2023-04-04 09:28 UTC, viktor-nonjme commented
Так много изменений потому что комп поменял. И папку проекта вместе с ним

Вот мои изменения:

[Здесь](https://github.com/boorav4ik/praktikum/pull/27/commits/a4ab715eba144a443dc3ac639f41cee351c9ce18)

2023-04-04 19:40 UTC, LapEv requested changes
1. пулл реквест только не в ветку main, а в develop
2. подтянулись, я так понимаю, абсолютно все коммиты. Возможно из-за п.1. Я не самый лучший подсказчик по гиту и как это исправить лучше ребята подскажут, как это исправить и предоставят свои комментарии по этому поводу.

2023-04-04 20:33 UTC, viktor-nonjme commented
> 1. пулл реквест только не в ветку main, а в develop
> 2. подтянулись, я так понимаю, абсолютно все коммиты. Возможно из-за п.1. Я не самый лучший подсказчик по гиту и как это исправить лучше ребята подскажут, как это исправить и предоставят свои комментарии по этому поводу.

1. Поменял
2. Синхронизировался с твоими последними изменениями. А что исправлять ? Всё смержится. Просто проект локально пришлось начать заново

2023-04-05 10:36 UTC, LapEv approved these changes

2023-04-05 17:55 UTC, tayru approved these changes

2023-04-06 12:54 UTC, EzhikTT requested changes

2023-04-06 12:54 UTC, EzhikTT commented on packages/client/src/components/FullScreen.tsx
> +    | undefined
Почему `undefined`?

2023-04-07 06:50 UTC, viktor-nonjme commented on packages/client/src/components/FullScreen.tsx
> +    | undefined
<img width="514" alt="Снимок экрана 2023-04-07 в 09 49 37" src="https://user-images.githubusercontent.com/57726054/230557250-0f25ff29-ee6f-4c4d-8934-fdfe00a7f30b.png">

2023-04-08 11:03 UTC, viktor-nonjme commented
- Добавлено аудио апи

<img width="1792" alt="Снимок экрана 2023-04-08 в 13 41 21" src="https://user-images.githubusercontent.com/57726054/230717676-be5bb105-f313-4c2b-88b7-e7684e02c03b.png">

2023-04-09 14:28 UTC, EzhikTT approved these changes
Все ок)

2023-04-09 15:09 UTC, tayru approved these changes

2023-04-10 08:34 UTC, LapEv approved these changes

2023-04-16 03:56 UTC, boorav4ik requested changes

2023-04-16 03:56 UTC, boorav4ik commented on packages/client/src/components/FullScreen.tsx
> +  const handleFullScreen = toggleFullScreen as | MouseEventHandler<HTMLButtonElement>
для чего ` |`?
Лучше будет определить тип возвращаемых значений из хука в самом хуке, тогда не придётся делать это везде, где используется хук.
Посмотри, как это сделано в `useAuth`

2023-04-16 03:56 UTC, boorav4ik commented on packages/client/src/components/FullScreen.tsx
> +        <Button
Для кнопок с иконками в  `mui` есть готовый компонент `IconButton`

2023-04-16 03:56 UTC, boorav4ik commented on packages/client/src/components/Audio.tsx
> +      <Button
используй `IconButton` для кнопок и с иконками
для всплывающих подсказок [`tooltip`](https://mui.com/material-ui/react-tooltip/)

2023-04-16 03:56 UTC, boorav4ik commented on packages/client/src/layouts/Main/icons/Audio.tsx
> +        stroke-linejoin="round"></path>
в jsx нужно писать `rokeWidth`, `rokeLinecap`, `rokeLinejoin`

2023-04-16 03:56 UTC, boorav4ik commented on packages/client/src/components/FullScreen.tsx
> +  ) as RefObject<DocumentElementWithFullScreen>
тип у хуков нужно указывать вот так:
 ```tsx
const fullScreenElement = useRef<DocumentElementWithFullScreen>(null)
```

2023-04-16 03:56 UTC, boorav4ik commented on packages/client/src/components/Audio.tsx
> +          <audio src={Track} controls loop></audio>
Лучше захайдить сам элемент `audio`, а вместо него показывать `IconButton` при нажатии на которую музыку можно включить/выключит
если музыка включена, при наведении на кнопку показывать [слайдер](https://mui.com/material-ui/react-slider) уровня громкости.
и для этих целей предлагаю рассмотреть использование [`FAB`](https://mui.com/material-ui/react-floating-action-button/)

2023-04-16 04:10 UTC, viktor-nonjme commented on packages/client/src/components/Audio.tsx
> +          <audio src={Track} controls loop></audio>
Используй ) Я функционал сделал, по очень размытому ТЗ. Работает? Работает. Исправлять и тешить твоё его не собираюсь

2023-04-16 04:10 UTC, merged