T 05 49 test on basic components
boorav4ik/praktikum pull request #29
Opened 2023-04-27 09:48 UTC by Replicatus

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-27 11:37 UTC, EzhikTT approved these changes
Все ок

2023-04-29 04:54 UTC, viktor-nonjme approved these changes

2023-05-01 11:22 UTC, LapEv approved these changes

2023-05-02 00:39 UTC, boorav4ik requested changes
Круто!

2023-05-02 00:39 UTC, boorav4ik commented on packages/client/src/components/Button/index.test.tsx
> +import {Button} from './index'
Отформатируй, плиз

2023-05-03 17:30 UTC, boorav4ik approved these changes

2023-05-03 17:32 UTC, merged