Feat/t 05 50 leaderboard
boorav4ik/praktikum pull request #31
Opened 2023-04-29 09:04 UTC by tayru

### Какую задачу решаем
Подключаем апишку лидербордов, пока в формате получения данных

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-04-29 09:41 UTC, boorav4ik requested changes
Молодец что разобрался с тулкитом. :+1:

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/api/user.ts
> +      console.log(response.data)
забыл убрать console.log

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/api/user.ts
> +  async (data: any, thunkAPI) => {
у тебя же есть описание типа для даты?
может назовём его рекорд? мне кажется по смыслу больше подходит

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/hooks/authActions.ts
> +  GetLeaderBoard: (data: any) => void
наверное, лучше использовать просто dispatch и useSelector, потому что нужно в одном компоненте

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/hooks/useAuth.tsx
>      },
этот хук для авторизации
ИМХО, для получения лидербордов из стора, нужно либо отдельный хук, либо просто useSelector использовать в реакт компоненте лидербордов.

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  const [{ leaderData }] = useAuth()
уже писал про useAuth

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +
забыл убрать console.log

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/hooks/useAuth.tsx
> +  GetLeaderBoard,
наверное, это ещё и отдельное api

2023-04-29 09:41 UTC, boorav4ik commented on packages/client/src/store/slices/auth/index.ts
>    },
нужно написать отдельный слайс

2023-04-29 20:35 UTC, tayru commented on packages/client/src/store/slices/auth/index.ts
>    },
слайс добавил

2023-04-29 21:52 UTC, tayru commented on packages/client/src/hooks/useAuth.tsx
> +  GetLeaderBoard,
сделал

2023-04-29 21:52 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +
убрал консольки

2023-04-29 21:52 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  const [{ leaderData }] = useAuth()
переделал

2023-04-29 21:53 UTC, tayru commented on packages/client/src/hooks/authActions.ts
> +  GetLeaderBoard: (data: any) => void
сделал

2023-04-30 15:10 UTC, LapEv requested changes

2023-04-30 15:10 UTC, LapEv commented on packages/client/src/api/leader.ts
> +      const response = await host.post<any[]>(
Думаю и здесь вместо any лучше указать тип Record

2023-04-30 15:10 UTC, LapEv commented on packages/client/src/api/leader.ts
> +  async (data: dataGetRecord[], thunkAPI) => {
поменять dataGetRecord[] на dataGetRecord. Тогда в LeaderboardPage не будет конфликта типов

2023-04-30 15:10 UTC, LapEv commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                score={item.data?.score}
если используешь перебор map для отрисовки компонентов необходимо добавлять ключи, что-то типа                 key={item.data?.name+index}. Как минимум, ругаться не будет.

2023-04-30 15:10 UTC, LapEv commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                score={item.data?.score}
если используешь перебор map для отрисовки компонентов необходимо добавлять ключи, что-то типа                 key={item.data?.name+index}. Как минимум, ругаться не будет.

2023-05-01 07:14 UTC, LapEv approved these changes

2023-05-01 18:42 UTC, Replicatus approved these changes

2023-05-02 06:52 UTC, viktor-nonjme approved these changes

2023-05-09 05:04 UTC, viktor-nonjme approved these changes

2023-05-10 17:22 UTC, LapEv requested changes

2023-05-10 17:50 UTC, boorav4ik requested changes

2023-05-10 17:50 UTC, boorav4ik commented on packages/client/src/components/Game/GameBoard.tsx
> +    }
все константы можно вынести в сам `UpdateUserLeader`

2023-05-10 17:50 UTC, boorav4ik commented on packages/client/src/api/leader.ts
> +export const GetLeaderBoard = createAsyncThunk(
название функций обычно пишут с маленькой буквы

2023-05-10 17:50 UTC, boorav4ik commented on packages/client/src/api/leader.ts
> +export const UpdateUserLeader = createAsyncThunk(
название функций обычно пишут с маленькой буквы

2023-05-10 17:50 UTC, boorav4ik commented on packages/client/src/api/leader.ts
> +  async (data: dataGetRecord, thunkAPI) => {
https://redux-toolkit.js.org/rtk-query/api/createApi
если есть желание, можешь поразбираться

2023-05-10 20:06 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                score={item.data?.score}
Сделано

2023-05-10 20:06 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                score={item.data?.score}
Сделано

2023-05-10 20:06 UTC, tayru commented on packages/client/src/api/leader.ts
> +      const response = await host.post<any>(
Сделано

2023-05-11 19:53 UTC, tayru commented on packages/client/src/api/leader.ts
> +export const UpdateUserLeader = createAsyncThunk(
поменял

2023-05-11 23:02 UTC, boorav4ik approved these changes

2023-05-12 14:53 UTC, LapEv approved these changes

2023-05-14 13:32 UTC, tayru commented on packages/client/src/api/leader.ts
> +export const GetLeaderBoard = createAsyncThunk(
+

2023-05-14 14:30 UTC, tayru commented on packages/client/src/components/Game/GameBoard.tsx
> +    }
+

2023-05-16 05:02 UTC, EzhikTT commented on packages/client/src/api/leader.ts
> +      const response = await host.post<any[]>(
Не лучше, а очень желательно. `any` вообще лучше не использовать, а описывать типы

2023-05-16 05:04 UTC, EzhikTT commented on packages/client/src/components/Game/GameBoard.tsx
> +    if (movedLayers.size) soundEffects && soundEffects.shift.play()
Лучше всегда ставить скобки. Повышает читаемость кода

2023-05-16 05:04 UTC, EzhikTT commented on packages/client/src/components/Game/GameBoard.tsx
> +      cells.forEach(([value], i) => {
Используйте циклы, а не этот старый и не оптимальный метод

2023-05-16 05:06 UTC, EzhikTT requested changes

2023-05-16 05:06 UTC, EzhikTT commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +  name: string | null | undefined
А не проще сделать его опциональным?

2023-05-17 16:21 UTC, tayru commented on packages/client/src/components/Game/GameBoard.tsx
> +    if (movedLayers.size) soundEffects && soundEffects.shift.play()
добавлено

2023-05-17 17:22 UTC, tayru commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +  name: string | null | undefined
переделал без null | undefined

2023-05-17 17:22 UTC, tayru commented on packages/client/src/components/Game/GameBoard.tsx
> +      cells.forEach(([value], i) => {
поменял на фор

2023-05-19 06:39 UTC, EzhikTT approved these changes
Все ок

2023-05-19 18:56 UTC, merged