Feat/t 05 52 database
boorav4ik/praktikum pull request #32
Opened 2023-05-01 21:07 UTC by LapEv

### Какую задачу решаем
База данных для форума
Форум

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/51084295/235531418-17ec5296-ac43-4c18-97b8-20c47b3effb9.png)
![image](https://user-images.githubusercontent.com/51084295/235531472-a4c01e62-1c2d-454a-be9d-b7e3b88939be.png)
![image](https://user-images.githubusercontent.com/51084295/235531510-03508e8d-7d9f-4f5c-8bd9-e721e76608ff.png)

### TBD (если есть)

2023-05-02 05:34 UTC, tayru approved these changes

2023-05-02 06:54 UTC, viktor-nonjme approved these changes

2023-05-10 04:10 UTC, Replicatus approved these changes

2023-05-10 04:10 UTC, Replicatus commented on packages/server/services/forumService.ts
> +  }
Зачем везде в запросах после удаления искать данный элемент, ведь он уже точно не найдется?

2023-05-10 11:35 UTC, LapEv commented on packages/server/services/forumService.ts
> +  }
чтобы вернуть на фронт обновленный список топиков. Я не конкретный топик ищу после удаления, а целиком хочу получить список топиков. На фронте столкнулся с проблемой обновления списка, пришлось бы костыли делать, а здесь две строчки и фронт обновляется сразу без проблем.

2023-05-10 16:45 UTC, boorav4ik requested changes

2023-05-10 19:12 UTC, LapEv commented on Dockerfile.server
> +COPY wait-for.sh wait-for.sh
убрал всё, что связано с wait-for.sh. Настроил через docker-compose.yml

2023-05-11 05:42 UTC, EzhikTT commented on packages/server/models/modelComment.ts
> +export interface IComment {
В дефолтном кодстайле `TypeScript` не рекомендуется добавлять букву `I` к интерфейсам

2023-05-11 05:43 UTC, EzhikTT requested changes

2023-05-11 05:43 UTC, EzhikTT commented on packages/server/services/forumService.ts
> +  }
А фронт не может вторым запросом запросить топики? После удаления

2023-05-11 23:04 UTC, boorav4ik approved these changes

2023-05-12 14:23 UTC, LapEv commented on packages/client/src/components/forum/icons/GarbageIcon.tsx
> +    </SvgIcon>
добавил material-icons, убрал svg

2023-05-12 14:29 UTC, LapEv commented on packages/client/src/pages/Forum/ThemeBranch.tsx
> +                </ColorButton>
Готово

2023-05-12 14:29 UTC, LapEv commented on packages/server/models/modelComment.ts
> +export interface IComment {
Исправлено

2023-05-16 05:07 UTC, EzhikTT approved these changes
Все ок

2023-05-16 10:41 UTC, merged