добавил ErrorBoundary
boorav4ik/praktikum pull request #35
Opened 2023-05-11 20:53 UTC by tayru

### Какую задачу решаем
добавил ErrorBoundary

### Скриншоты/видяшка (если есть)
![image](https://github.com/boorav4ik/praktikum/assets/20746367/82a6e96a-9f80-438c-b6ec-5615da72d6cf)

### TBD (если есть)

2023-05-11 23:00 UTC, boorav4ik requested changes

2023-05-13 08:01 UTC, viktor-nonjme approved these changes

2023-05-13 08:05 UTC, LapEv approved these changes

2023-05-13 10:06 UTC, Replicatus approved these changes

2023-05-14 13:16 UTC, tayru commented on packages/client/src/App.tsx
> +          </ErrorBoundary>
сделал

2023-05-14 13:16 UTC, tayru commented on packages/client/src/App.tsx
> +import ErrorBoundary from 'components/ErrorBoundary/ErrorBoundary'
сделал

2023-05-14 13:25 UTC, tayru commented on packages/client/src/components/ErrorBoundary/ErrorBoundary.tsx
> +}
![image](https://github.com/boorav4ik/praktikum/assets/20746367/e2716f27-2465-46dc-b869-5b7d0d6b5ba9)
Добавил

2023-05-16 05:19 UTC, EzhikTT approved these changes
Все ок

2023-05-17 14:18 UTC, boorav4ik approved these changes

2023-05-17 18:28 UTC, merged