Feat/t05 17 profile page
boorav4ik/praktikum pull request #4
Opened 2023-02-26 17:54 UTC by LapEv

### Какую задачу решаем

Создание страницы Профиля. Редактирование полей данных пользователя, сохранение, отмена. Загрузка аватара.

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/51084295/221427485-d5ab666b-4e87-44c4-b59b-db29520af7a6.png)
![image](https://user-images.githubusercontent.com/51084295/221427498-3f86dfa1-e334-4f99-9b15-59b7f314bcc5.png)

### TBD (если есть)

2023-02-27 07:25 UTC, boorav4ik reviewed
можешь сделать ребэйс на девелоп

2023-02-27 07:25 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileFields.tsx
> +  const [text, setText] = useState<string>(value)
Это лишний `useState`, его можно убрать, в `TextField` можно сразу передавать `value` из `props`, а из `onChange` можно убрать `setText(event.target.value)`
Этот `useState` будет вызывать дополнительну перерисовку компонента.

2023-02-27 07:25 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileFooter.tsx
> +  const [editButtonName, setEditButtonNanme] = useState<string>('Редактировать')
Опечатка `setEditButtonNanme`

2023-02-27 07:25 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileFooter.tsx
> +  const [editButtonName, setEditButtonNanme] = useState<string>('Редактировать')
Будет лучше, если не использовать тут дополнительные `useState`.
А имя кнопки можно задать так:
```ts
<Button onClick={checkSave}>{editStatus === 'info' ? 'Играть!' : 'Отмена'}</Button>
<Button onClick={checkCancel}>{editStatus === 'info' ? 'Редактировать' : 'Сохранить'}</Button>
```
Меньше изменений стэйта, меньше рендеринга

2023-02-27 07:25 UTC, boorav4ik commented on packages/client/src/pages/Profile/ProfileMain.tsx
> +  const [newUserData, setNewUserData] = useState<object>(user)
тоже самое, лишний useState)) [вот что об это пишут в документации `react`](https://ru.reactjs.org/docs/lifting-state-up.html#lessons-learned)

Сейчас, пока у нас не прикручен `redux` и нет никакого `api`, для `cancelButton` батон можно пробросить `handle`, который просто возвращает дефолтные значения. А потом мы его перепишем, так чтоб он забирал данные со `store`, например

2023-02-27 19:42 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileMain.tsx
> +  const [newUserData, setNewUserData] = useState<object>(user)
Да, я уже голову сломал без редакса, чтобы всё работало. :) я предлагаю, дождаться redux и допилить этот функционал.

2023-02-27 19:46 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileFields.tsx
> +  const [text, setText] = useState<string>(value)
Готово

2023-02-27 19:47 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileFooter.tsx
> +  const [editButtonName, setEditButtonNanme] = useState<string>('Редактировать')
Готово

2023-02-27 19:47 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileFooter.tsx
> +  const [editButtonName, setEditButtonNanme] = useState<string>('Редактировать')
Готово.

2023-02-28 09:31 UTC, EzhikTT commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +      <label htmlFor="avatar-icon-file">
Можно `input` класть внутрь `label`, тогда не нужен будет `htmlFor`

2023-02-28 09:33 UTC, EzhikTT requested changes

2023-02-28 09:33 UTC, EzhikTT commented on packages/client/src/App.tsx
> +import { ProfilePage } from './pages/Profile/Profile'
А почему не сделать индексную страницу, чтобы был импорт красивый?

2023-02-28 12:53 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileHeader.tsx
> +      <label htmlFor="avatar-icon-file">
Готово

2023-02-28 12:53 UTC, LapEv commented on packages/client/src/pages/Profile/ProfileMain.tsx
> +    if (editStatus === 'cancel') {
Готово

2023-02-28 12:53 UTC, LapEv commented on packages/client/src/App.tsx
> +import { ProfilePage } from './pages/Profile/Profile'
Готово

2023-03-01 13:23 UTC, EzhikTT approved these changes
Все ок, но команда должна быть все в ревьюерах и апрувнуть

2023-03-02 06:00 UTC, boorav4ik approved these changes

2023-03-05 20:03 UTC, merged