Feat/t05 28 side bar
boorav4ik/praktikum pull request #6
Opened 2023-03-01 21:02 UTC by LapEv

### Какую задачу решаем
Создание AppBar, SideBar + NavBar с возможностью скрытия SideBar (Responsive drawer)

### Скриншоты/видяшка (если есть)

![image](https://user-images.githubusercontent.com/51084295/222264136-6fb5ba5c-d062-40a2-8533-f46c97832688.png)
![image](https://user-images.githubusercontent.com/51084295/222264188-ed520c41-4fbd-473a-9201-87619f29f7cb.png)

### TBD (если есть)

2023-03-02 13:09 UTC, EzhikTT requested changes

2023-03-02 13:09 UTC, EzhikTT commented on packages/client/src/components/drawerBar/icons/Forum.tsx
> +const D =
А зачем вынесли в отдельную переменную, если выше не выносили?

2023-03-02 17:15 UTC, LapEv commented on packages/client/src/components/drawerBar/icons/Forum.tsx
> +const D =
Переделал, чтобы всё было в компоненте без выноса в отдельную переменную.

2023-03-04 07:55 UTC, boorav4ik approved these changes

2023-03-04 08:21 UTC, EzhikTT approved these changes
Все ок

2023-03-04 08:52 UTC, boorav4ik commented
может переделаем, чтоб боковая панель не сдвигала навбар
вот накидал [пример](https://stackblitz.com/edit/react-wvxnty) как это можно сделать
![Снимок экрана от 2023-03-04 11-46-32](https://user-images.githubusercontent.com/67604789/222886514-b341359b-c3bd-4fc3-a45a-82b7676bedca.png)

2023-03-05 19:19 UTC, merged