Feat/t05 16 leaderboard
boorav4ik/praktikum pull request #9
Opened 2023-03-06 13:35 UTC by tayru

### Какую задачу решаем
Верстка страницы лидерборда

### Скриншоты/видяшка (если есть)
![image](https://user-images.githubusercontent.com/20746367/223124937-946dcbed-354b-4baf-ac37-7a2cb410b00f.png)

### TBD (если есть)

2023-03-06 17:28 UTC, LapEv reviewed
В целом мне  всё понятно в коде, быстро в нем разобрался. 
В дальнейшем надо будет store подкрутить и этот компонент будет готов

2023-03-06 17:40 UTC, LapEv approved these changes

2023-03-06 21:07 UTC, LapEv commented on packages/client/src/App.tsx
>          </Routes>
Чтобы в дальнейшем смержить ветку необходимо убрать конфликт с веткой develop "This branch has conflicts that must be resolved"
Для этого надо добавить DrawerBar. Вот только я не знаю, будет ли конфликт со строкой 
<Route path='/leaderboard' element={<LeaderboardPage />} />
У меня было такое с моей веткой Profile page, добавил Drawer, потому что он уже App.tsx был. Но правда и мой роутер Profile Page тоже уже был. 
Но также, Drawer надо подтягивать в App.tsx, а для этого надо скорее всего подтянуть всё из feat/T05-28-SideBar или develop, потому что там есть уже есть всё, что касается Drawer. Прежде чем делать, лучше проконсультироваться. 
Я могу рассказать, как я с этим экспериментировал. Я создал копию локальной папки проекта, после чего начал подтягивать ветки поочередно и смотрел, что в итоге выдаю перед пушом. Если видел ошибки, возвращал всё назад.  Опять же, если не уверен в том, что делаешь, то лучше это обсудить с нами в общем чате или куратором.
С этим конфликтом он не даст смержить ветку.

2023-03-07 11:26 UTC, EzhikTT commented on packages/client/src/App.tsx
>          </Routes>
Конфликты, обычно, решаются так:
1) переходят на ветку, в которую вливают
2) пуллят ее
3) переходят на ветку, которую влить хотят
4) мержат в нее локально ветку из п1
5) решают локально конфликты и пушат коммит
6) он сам подтянется в ПР и будет красиво

2023-03-07 11:27 UTC, EzhikTT commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +const gamers1 = [
Можно было бы для красоты вынести в отдельные мок файлы, чтобы было красивее

2023-03-07 11:28 UTC, EzhikTT requested changes

2023-03-07 11:28 UTC, EzhikTT commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +export function LeaderboardPage() {
Почему где-то стрелочные функции, где-то полноценные?

2023-03-07 11:28 UTC, EzhikTT commented on packages/client/src/pages/Leaderboard/LeaderHeader.tsx
> +export const LeaderHeader: FC<any> = (
А почему объявлен интерфейс, но не используется?

2023-03-09 19:43 UTC, boorav4ik requested changes

2023-03-09 19:43 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +}
[JSX](https://ru.reactjs.org/docs/introducing-jsx.html#embedding-expressions-in-jsx)  позволяет писать вместо 
```jsx
const Item  = (props) => {
  retutn (
    <Element {...props} />
  )
}
```
написать
```jsx
const Item = (props) => (
  <Element {...props} />
)
```
это не обязательно, просто выглядит лучше.
А вообще, [как написано ниже](https://github.com/boorav4ik/praktikum/pull/9/files#r1127719818), лучше в одном проекте придерживаться какого-то одно стиля для объявления компонентов, либо стрелочные функции, либо обычные. Тоже касается функционального и классового стиля. Конечно, исключения допустимы, там где это чем-то обоснованно.

2023-03-10 12:56 UTC, boorav4ik requested changes

2023-03-10 12:56 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +import Typography from "@mui/material/Typography";
Где-то стоят `;` в конце строк
[У нас в проекте их не должно быть](https://github.com/boorav4ik/praktikum/blob/main/.prettierrc#L3)
Тоже самое по поводу кавычек: [должны быть одинарные](https://github.com/boorav4ik/praktikum/blob/main/.prettierrc#L5)
не забывай форматировать текст перед заливкой

2023-03-10 18:10 UTC, viktor-nonjme approved these changes

2023-03-10 21:22 UTC, tayru commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +import Typography from "@mui/material/Typography";
Исправил

2023-03-11 05:33 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +const gamers1 = [
Сделано

2023-03-11 07:15 UTC, boorav4ik requested changes

2023-03-11 07:15 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +        m: '0',
ноль можно передать числом, а не строкой

2023-03-11 07:15 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +        mb: '15px',
кажется тут отступы можно вообще убрать, у тебя отступы между блоками задаются [свойством spasing в Stack](https://github.com/boorav4ik/praktikum/pull/9/files#diff-736d975da0200988b1f53be715916abfb510fc7c6fe41ceb68dcfaf69a03445aR43)

2023-03-11 07:55 UTC, Replicatus approved these changes

2023-03-11 08:29 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +export function LeaderboardPage() {
убрал стрелки

2023-03-11 08:29 UTC, tayru commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +import { Box, Container, Stack, Divider, Grid } from '@mui/material'
убрал

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/LeaderHeader.tsx
> +export const LeaderHeader: FC<any> = () => {
переделал

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/LeaderHeader.tsx
> +}
убрал

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/LeaderHeader.tsx
> +import Typography, { TypographyProps } from '@mui/material/Typography'
убрал

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/LeaderHeader.tsx
> +import React, { FC } from 'react'
убрал

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +        mb: '15px',
убрал

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +  number: number,
сделано

2023-03-11 08:30 UTC, tayru commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +import React, { FC, useState, useEffect } from 'react'
убрал

2023-03-11 08:52 UTC, boorav4ik requested changes

2023-03-11 08:52 UTC, boorav4ik commented on packages/client/src/pages/Leaderboard/ItemLeader.tsx
> +import Typography from '@mui/material/Typography'
И `Box`, и `Typography`  импортятся из `@mui/material`
Приведи импорт к какому-то одному варианту

2023-03-11 10:13 UTC, boorav4ik approved these changes

2023-03-13 05:51 UTC, EzhikTT requested changes

2023-03-13 05:51 UTC, EzhikTT commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +export function LeaderboardPage() {
А почему не наоборот? Какие у вас внутренние договоренности?

2023-03-14 12:34 UTC, merged